# -*- coding: utf-8 -*-
import json

import requests

payload = {'changes': {'description': {'current': '2', 'previous': '1'},
             'last_edited_at': {'current': '2018-10-09 03:04:54 UTC',
                                'previous': '2018-10-09 02:59:05 UTC'},
             'updated_at': {'current': '2018-10-09 03:04:54 UTC',
                            'previous': '2018-10-09 02:59:05 UTC'}},
 'event_type': 'merge_request',
 'labels': [],
 'object_attributes': {'action': 'update',
                       'assignee_id': None,
                       'author_id': 18,
                       'created_at': '2018-10-08 08:06:31 UTC',
                       'description': '2',
                       'head_pipeline_id': None,
                       'human_time_estimate': None,
                       'human_total_time_spent': None,
                       'id': 18738,
                       'iid': 3713,
                       'last_commit': {'author': {'email': 'chen.lei@qianka.com',
                                                  'name': '陈磊'},
                                       'id': 'b166df3e0d1aa60e8539caad3deeb2ab78b74270',
                                       'message': 'add flake8 to Makefile\n',
                                       'timestamp': '2018-10-09T02:43:39Z',
                                       'url': 'https://git.corp.qianka.com/v4/hebe/commit/b166df3e0d1aa60e8539caad3deeb2ab78b74270'},
                       'last_edited_at': '2018-10-09 03:04:54 UTC',
                       'last_edited_by_id': 18,
                       'merge_commit_sha': None,
                       'merge_error': None,
                       'merge_params': {'force_remove_source_branch': '1'},
                       'merge_status': 'can_be_merged',
                       'merge_user_id': None,
                       'merge_when_pipeline_succeeds': False,
                       'milestone_id': None,
                       'source': {'avatar_url': None,
                                  'ci_config_path': None,
                                  'default_branch': 'master',
                                  'description': '',
                                  'git_http_url': 'https://git.corp.qianka.com/v4/hebe.git',
                                  'git_ssh_url': 'git@git.corp.qianka.com:v4/hebe.git',
                                  'homepage': 'https://git.corp.qianka.com/v4/hebe',
                                  'http_url': 'https://git.corp.qianka.com/v4/hebe.git',
                                  'id': 727,
                                  'name': 'hebe',
                                  'namespace': 'v4',
                                  'path_with_namespace': 'v4/hebe',
                                  'ssh_url': 'git@git.corp.qianka.com:v4/hebe.git',
                                  'url': 'git@git.corp.qianka.com:v4/hebe.git',
                                  'visibility_level': 10,
                                  'web_url': 'https://git.corp.qianka.com/v4/hebe'},
                       'source_branch': 'android-subtask-complete',
                       'source_project_id': 727,
                       'state': 'opened',
                       'target': {'avatar_url': None,
                                  'ci_config_path': None,
                                  'default_branch': 'master',
                                  'description': '',
                                  'git_http_url': 'https://git.corp.qianka.com/v4/hebe.git',
                                  'git_ssh_url': 'git@git.corp.qianka.com:v4/hebe.git',
                                  'homepage': 'https://git.corp.qianka.com/v4/hebe',
                                  'http_url': 'https://git.corp.qianka.com/v4/hebe.git',
                                  'id': 727,
                                  'name': 'hebe',
                                  'namespace': 'v4',
                                  'path_with_namespace': 'v4/hebe',
                                  'ssh_url': 'git@git.corp.qianka.com:v4/hebe.git',
                                  'url': 'git@git.corp.qianka.com:v4/hebe.git',
                                  'visibility_level': 10,
                                  'web_url': 'https://git.corp.qianka.com/v4/hebe'},
                       'target_branch': 'master',
                       'target_project_id': 727,
                       'time_estimate': 0,
                       'title': '!!不要合并，测试CI!!',
                       'total_time_spent': 0,
                       'updated_at': '2018-10-09 03:04:54 UTC',
                       'updated_by_id': 18,
                       'url': 'https://git.corp.qianka.com/v4/hebe/merge_requests/3426',
                       'work_in_progress': False},
 'object_kind': 'merge_request',
 'project': {'avatar_url': None,
             'ci_config_path': None,
             'default_branch': 'master',
             'description': '',
             'git_http_url': 'https://git.corp.qianka.com/v4/hebe.git',
             'git_ssh_url': 'git@git.corp.qianka.com:v4/hebe.git',
             'homepage': 'https://git.corp.qianka.com/v4/hebe',
             'http_url': 'https://git.corp.qianka.com/v4/hebe.git',
             'id': 727,
             'name': 'hebe',
             'namespace': 'v4',
             'path_with_namespace': 'v4/hebe',
             'ssh_url': 'git@git.corp.qianka.com:v4/hebe.git',
             'url': 'git@git.corp.qianka.com:v4/hebe.git',
             'visibility_level': 10,
             'web_url': 'https://git.corp.qianka.com/v4/hebe'},
 'repository': {'description': '',
                'homepage': 'https://git.corp.qianka.com/v4/hebe',
                'name': 'hebe',
                'url': 'git@git.corp.qianka.com:v4/hebe.git'},
 'user': {'avatar_url': 'https://secure.gravatar.com/avatar/b6890987668c214be249e6eacc17a7bf?s=80&d=identicon',
          'name': '陈磊',
          'username': 'chenlei'}}

body = json.dumps(payload)


headers = {
    'Content-Type': 'application/json',
}

url = 'http://localhost:4399/qk-ci/gitlab-webhook'
# url = 'http://n1386.ops.gaoshou.me:4399/qk-ci/gitlab-webhook'
_ = requests.post(url, data=body, headers=headers)

print(_.status_code)
print(_.text)
